name: ez_list_view
description: A crash-safe ListView that automatically handles unbounded height constraints in Columns and Rows.
version: 0.0.3
homepage: https://github.com/Evgenii-Zinner/ez-list-view
repository: https://github.com/Evgenii-Zinner/ez-list-view
issue_tracker: https://github.com/Evgenii-Zinner/ez-list-view/issues
documentation: https://flutter.ezinner.com/ez_list_view
topics:
  - flutter
  - ez-flutter
  - listview
  - layout
  - scrollable
funding:
  - https://github.com/sponsors/Evgenii-Zinner/
  - https://thanks.dev/u/gh/evgenii-zinner
  - https://buymeacoffee.com/evgeniizinner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
